version: '3.8'

services:
  phanes-api:
    image: leev2/phanes-api
    command: uvicorn main:app --host 0.0.0.0 --port 91 --reload
    volumes:
      - C:/Users/Lee/Documents/Phanes/app:/app
    ports:
      - "4000:91"
    environment:
      - PYTHONUNBUFFERED=1
